### ISSUE TITLE
Build the Team's skills in writing accessible content

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/.github#25]
```[tasklist]
### Tasks
- [ ] geobtaa/gin#6
- [ ] https://github.com/geobtaa/.github/issues/24
- [ ] https://github.com/geobtaa/.github/issues/23
- [ ] https://github.com/geobtaa/gin/issues/7
```
