### ISSUE TITLE
Develop priority projects matrix

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/.github#32]
```[tasklist]
### Tasks
- [ ] https://github.com/geobtaa/.github/issues/31
- [ ] https://github.com/geobtaa/.github/issues/30
- [ ] https://github.com/geobtaa/.github/issues/29
- [ ] https://github.com/geobtaa/.github/issues/28
- [ ] https://github.com/geobtaa/.github/issues/27
```

**Comment by karenmajewicz** [comment]
https://docs.google.com/spreadsheets/d/1PeweXG4kffj3QdOsRK-QBFreROPiM8v4gc6evI8e-7g/edit#gid=545256296
