### ISSUE TITLE
Migrate public facing documents to accessible format

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/.github#46]
```[tasklist]
### Tasks
- [ ] https://github.com/geobtaa/gin/issues/3
- [ ] https://github.com/geobtaa/.github/issues/45
- [ ] https://github.com/geobtaa/.github/issues/44
- [ ] https://github.com/geobtaa/gin/issues/5
- [ ] https://github.com/geobtaa/.github/issues/42
- [ ] https://github.com/geobtaa/.github/issues/43
```
