### ISSUE TITLE
Add policies and disclaimers to Geoportal

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/.github#70]
"
```[tasklist]
### Tasks
- [ ] https://github.com/geobtaa/geoportal/issues/614
- [ ] https://github.com/geobtaa/geoportal/issues/615
- [ ] https://github.com/geobtaa/geoportal/issues/616
- [ ] https://github.com/geobtaa/geoportal/issues/617
- [ ] https://github.com/geobtaa/geoportal/issues/598
```

**Comment by karenmajewicz** [comment]
Draft of new policies and layout is in dev https://geodev.btaa.org/?search_field=all_fields&q=
